# permissions for end users to edit dnsrecords.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dnsrecord-editor-role
rules:
- apiGroups:
  - dns.linka.cloud
  resources:
  - dnsrecord
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.linka.cloud
  resources:
  - dnsrecord/status
  verbs:
  - get
