# permissions for end users to view dnsrecord.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dnsrecord-viewer-role
rules:
- apiGroups:
  - dns.linka.cloud
  resources:
  - dnsrecord
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dns.linka.cloud
  resources:
  - dnsrecord/status
  verbs:
  - get
